"""OpenAPI 3.1 spec for nthlayer-core's HTTP API.

The OPENAPI dict below is the source of truth. Twin artefacts:

  - Runtime: GET /openapi.json serves OPENAPI as JSON.
  - Static:  docs/api/openapi.json (regenerated by scripts/regen_openapi.py).

Drift detection: tests/test_openapi.py asserts every Starlette route in
server.routes appears in OPENAPI["paths"] and vice versa. Adding a new
route without updating the spec fails CI.

Per-path-group fragments live in nthlayer_core._openapi.paths_*; this
module aggregates them. Phases 2-4 (tu04.1.2/3/4) each add one fragment
module and one import line below.

Bead: opensrm-tu04.1.1 (Phase 1, framework + /health).
"""
from __future__ import annotations

from typing import Any

from nthlayer_core._openapi import paths_health

# Aggregate per-group fragments. New phases append to this list.
_FRAGMENTS = [
    paths_health,
    # paths_verdicts,            # tu04.1.2
    # paths_assessments_cases,   # tu04.1.3
    # paths_other,               # tu04.1.4
]


def _build_paths() -> dict[str, dict[str, Any]]:
    paths: dict[str, dict[str, Any]] = {}
    for fragment in _FRAGMENTS:
        for path, item in fragment.PATHS.items():
            if path in paths:
                raise ValueError(
                    f"Duplicate OpenAPI path entry: {path!r} declared in "
                    f"multiple paths_*.py fragments"
                )
            paths[path] = item
    return paths


def _build_schemas() -> dict[str, dict[str, Any]]:
    # Shared components. ErrorEnvelope is referenced by every 4xx/5xx
    # response across the API.
    schemas: dict[str, dict[str, Any]] = {
        "ErrorEnvelope": {
            "type": "object",
            "required": ["error"],
            "properties": {
                "error": {
                    "type": "string",
                    "description": (
                        "Machine-readable error code. Handlers raise a fixed "
                        "vocabulary of codes documented per-endpoint. The "
                        "internal_error code is used when the store layer "
                        "raises an unexpected exception (opensrm-9uow.1)."
                    ),
                },
                "detail": {
                    "type": "object",
                    "description": (
                        "Structured detail. Shape varies by error code and "
                        "endpoint. Operators read structured server logs for "
                        "the canonical diagnosis; clients use this for "
                        "user-facing messages."
                    ),
                    "additionalProperties": True,
                },
            },
            "additionalProperties": False,
        },
    }
    for fragment in _FRAGMENTS:
        for name, schema in fragment.SCHEMAS.items():
            if name in schemas:
                raise ValueError(
                    f"Duplicate OpenAPI schema component: {name!r} declared "
                    f"in multiple paths_*.py fragments"
                )
            schemas[name] = schema
    return schemas


OPENAPI: dict[str, Any] = {
    "openapi": "3.1.0",
    "info": {
        "title": "NthLayer Core API",
        "version": "1.6.0",
        "description": (
            "Tier-1 reliability-critical HTTP API: verdict store, case "
            "management, manifest catalogue, heartbeats, component state. "
            "Workers and bench access the store exclusively through these "
            "endpoints. Verdicts are immutable after creation; outcome "
            "resolution writes a new verdict referencing the original as "
            "parent."
        ),
    },
    "servers": [
        {"url": "/", "description": "Same-origin"},
    ],
    "paths": _build_paths(),
    "components": {
        "schemas": _build_schemas(),
    },
}


def _spec_path_method_pairs() -> set[tuple[str, str]]:
    """Return {(path, METHOD)} pairs declared in OPENAPI['paths']."""
    out: set[tuple[str, str]] = set()
    for path, item in OPENAPI["paths"].items():
        for method in item.keys():
            # OpenAPI Path Item keys may include non-method keys
            # (parameters, summary, description); guard with a known set.
            if method.lower() in {"get", "post", "put", "delete", "patch", "head", "options"}:
                out.add((path, method.upper()))
    return out


def _route_spec_pairs() -> set[tuple[str, str]]:
    """Return {(path, METHOD)} pairs declared in server.routes.

    Excludes the /openapi.json route itself — that route is added in
    Task 4 and is not documented as part of the API (it IS the API
    documentation).
    """
    from nthlayer_core.server import routes  # noqa: PLC0415 — avoid import cycle at module load
    out: set[tuple[str, str]] = set()
    for r in routes:
        path = getattr(r, "path", None)
        methods = getattr(r, "methods", None) or set()
        if path is None or not methods:
            continue
        if path == "/openapi.json":
            continue
        for m in methods:
            if m == "HEAD":
                # Starlette adds HEAD for free on GET routes — don't
                # require it in the spec.
                continue
            out.add((path, m.upper()))
    return out


def assert_parity() -> None:
    """Raise AssertionError if routes and spec drift.

    Used by tests/test_openapi.py and optionally at server startup. The
    error message lists both sides so the fix is obvious from CI logs.
    """
    spec = _spec_path_method_pairs()
    routes = _route_spec_pairs()
    only_in_routes = routes - spec
    only_in_spec = spec - routes
    if only_in_routes or only_in_spec:
        raise AssertionError(
            "OpenAPI spec / server.routes parity violated.\n"
            f"  In routes but not spec: {sorted(only_in_routes)}\n"
            f"  In spec but not routes: {sorted(only_in_spec)}\n"
            "Add/remove entries in src/nthlayer_core/_openapi/paths_*.py "
            "to restore parity."
        )
